import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {Connector} from '../src/connector.mjs';
async function fixture(t){const dir=await mkdtemp(path.join(tmpdir(),'dot-test-'));t.after(()=>rm(dir,{recursive:true,force:true}));await writeFile(path.join(dir,'session.json'),JSON.stringify({session:'s',className:'dot-connector-00000000-0000-0000-0000-000000000000',paneId:4,windowId:2,guiPid:123,guiStartTicks:'123456789',guiExecutable:'C:\\wezterm\\wezterm-gui.exe',socketPath:'C:\\runtime\\gui-sock-123'}));await writeFile(path.join(dir,'INPUT_ENABLED'),'1');const writes=[];let hook=()=>{};const c=new Connector({exe:'C:\\wezterm\\wezterm.exe',stateDir:dir,identity:async s=>({...s}),invoke:async(exe,args,input,env)=>{if(args.includes('list')){await hook();return JSON.stringify([{pane_id:4,window_id:2}]);}if(args.includes('get-text'))return 'x'.repeat(20000);writes.push({args,input,env});return '';}});return {c,dir,writes,setHook:f=>hook=f};}
test('bounded snapshot, strict identity, paste != submit, persistent no-retry journal',async t=>{const {c,writes}=await fixture(t);await assert.rejects(c.snapshot(5),/mismatch/);let s=await c.snapshot(4);assert.equal(s.text.length,16000);assert.equal(s.truncated,true);await c.write({paneId:4,snapshotId:s.snapshotId,operationId:'a',kind:'paste',text:'hello'});assert.equal(writes[0].input,'hello');assert.ok(!writes[0].args.includes('--no-paste'));assert.ok(writes[0].args.includes('4'));s=await c.snapshot(4);await assert.rejects(c.write({paneId:4,snapshotId:s.snapshotId,operationId:'a',kind:'paste',text:'hello'}),/EEXIST/);await c.write({paneId:4,snapshotId:s.snapshotId,operationId:'b',kind:'submit'});assert.equal(writes[1].input,'\r');assert.ok(writes[1].args.includes('--no-paste'));});
test('controls cannot sneak submit into paste; stale snapshot rejected',async t=>{const {c,writes}=await fixture(t);const s=await c.snapshot(4);for(const text of ['a\nb','x\r','\x1b[200~','x\x85'])await assert.rejects(c.write({paneId:4,snapshotId:s.snapshotId,operationId:'a',kind:'paste',text}),/controls/);c.snapshots.get(s.snapshotId).time=0;await assert.rejects(c.write({paneId:4,snapshotId:s.snapshotId,operationId:'b',kind:'submit'}),/fresh/);assert.equal(writes.length,0);});
test('pause during pane validation cancels dispatch; no queued overlapping writes',async t=>{const {c,writes,setHook}=await fixture(t);const s=await c.snapshot(4);let release;setHook(()=>new Promise(r=>release=r));const first=c.write({paneId:4,snapshotId:s.snapshotId,operationId:'a',kind:'paste',text:'hello'});while(!release)await new Promise(r=>setImmediate(r));await assert.rejects(c.write({paneId:4,snapshotId:s.snapshotId,operationId:'b',kind:'submit'}),/busy/);await c.pause();release();await assert.rejects(first,/pause active/);assert.equal(writes.length,0);});
test('unknown dispatch outcome is not retried, including after server restart',async t=>{const {c,dir}=await fixture(t);const original=c.invoke;let attempts=0;c.invoke=async(...args)=>{if(args[1].includes('send-text')){attempts++;throw Error('timeout: outcome unknown');}return original(...args);};let s=await c.snapshot(4);await assert.rejects(c.write({paneId:4,snapshotId:s.snapshotId,operationId:'once',kind:'submit'}),/unknown/);const restarted=new Connector({exe:c.exe,stateDir:dir,invoke:c.invoke,identity:c.identity});s=await restarted.snapshot(4);await assert.rejects(restarted.write({paneId:4,snapshotId:s.snapshotId,operationId:'once',kind:'submit'}),/EEXIST/);assert.equal(attempts,1);});
test('PID reuse or mismatched GUI identity fails before CLI, with no fallback',async t=>{const {c}=await fixture(t);let calls=0;const original=c.invoke;c.invoke=async(...a)=>{calls++;return original(...a);};for(const field of ['guiPid','guiStartTicks','guiExecutable','className','socketPath']){c.identity=async s=>({...s,[field]:field==='guiPid'?999:'different'});await assert.rejects(c.snapshot(4),/identity changed/);}assert.equal(calls,0);});
test('each CLI uses only owned socket and preserves unrelated environment context',async t=>{const {c,writes}=await fixture(t);const before=process.env.WEZTERM_UNIX_SOCKET;const s=await c.snapshot(4);await c.write({paneId:4,snapshotId:s.snapshotId,operationId:'socket',kind:'paste',text:'hello'});assert.equal(writes[0].env.WEZTERM_UNIX_SOCKET,'C:\\runtime\\gui-sock-123');assert.ok(writes[0].env.WSLENV.split(':').includes('WEZTERM_UNIX_SOCKET/w'));assert.equal(process.env.WEZTERM_UNIX_SOCKET,before);});
test('a disappeared owned pane cannot be replaced by another window',async t=>{const {c,writes}=await fixture(t);const s=await c.snapshot(4);const original=c.invoke;c.invoke=async(...args)=>args[1].includes('list')?JSON.stringify([{pane_id:4,window_id:99}]):original(...args);await assert.rejects(c.write({paneId:4,snapshotId:s.snapshotId,operationId:'lost',kind:'submit'}),/owned pane missing/);assert.equal(writes.length,0);});

test('input defaults to paused and unreadable or malformed enable state denies dispatch',async t=>{const {c,dir,writes}=await fixture(t);for(const mode of ['missing','invalid','directory']){await rm(path.join(dir,'INPUT_ENABLED'),{recursive:true,force:true});if(mode==='invalid')await writeFile(path.join(dir,'INPUT_ENABLED'),'yes');if(mode==='directory')await mkdir(path.join(dir,'INPUT_ENABLED'));const s=await c.snapshot(4);assert.equal(s.paused,true);await assert.rejects(c.write({paneId:4,snapshotId:s.snapshotId,operationId:mode,kind:'submit'}),/pause active/);}assert.equal(writes.length,0);});
test('resume generation invalidates old snapshots, including during final identity query',async t=>{const {c,dir,writes}=await fixture(t);let s=await c.snapshot(4);await writeFile(path.join(dir,'INPUT_ENABLED'),'2');await assert.rejects(c.write({paneId:4,snapshotId:s.snapshotId,operationId:'old',kind:'submit'}),/generation changed/);s=await c.snapshot(4);let calls=0;c.identity=async state=>{if(++calls===2)await writeFile(path.join(dir,'INPUT_ENABLED'),'3');return state;};await assert.rejects(c.write({paneId:4,snapshotId:s.snapshotId,operationId:'race',kind:'submit'}),/generation changed/);assert.equal(writes.length,0);});
test('separate servers cannot overlap writes; abandoned lock fails closed',async t=>{const {c,dir,writes,setHook}=await fixture(t);const other=new Connector({exe:c.exe,stateDir:dir,invoke:c.invoke,identity:c.identity});const a=await c.snapshot(4),b=await other.snapshot(4);let release;setHook(()=>new Promise(r=>release=r));const first=c.write({paneId:4,snapshotId:a.snapshotId,operationId:'one',kind:'paste',text:'hello'});while(!release)await new Promise(r=>setImmediate(r));await assert.rejects(other.write({paneId:4,snapshotId:b.snapshotId,operationId:'two',kind:'submit'}),/EEXIST/);release();await first;assert.equal(writes.length,1);await mkdir(path.join(dir,'input.lock'));await assert.rejects(other.write({paneId:4,snapshotId:b.snapshotId,operationId:'crashed',kind:'submit'}),/EEXIST/);assert.equal(writes.length,1);});
