import {test} from 'node:test';import assert from 'node:assert/strict';import {evaluateRegistrationModel,rejectUntrustedRegistration} from '../src/cooperative-registration.mjs';
function fixture(){const claim={paneId:'pane-1',consoleId:'console-1',clientPid:2,clientStartTicks:'100',hostPid:3,hostStartTicks:'99',expiresAtMs:14000,generation:'g1',ownerId:'owner1',logonSessionId:'login1',clientImage:'wsl.exe',wsl:{distroId:'distro1',bootId:'boot1',pid:4,startTicks:'101',tty:'/dev/pts/2',sessionId:'session1'}};return {evidenceMode:'synthetic',revoked:false,claim,observation:{...structuredClone(claim),observedAtMs:10000,paneBindings:['pane-1']}};}
const check=m=>evaluateRegistrationModel(m,11000);
test('self-declared consistent JSON never creates registration or input capability',()=>{const r=check(fixture());assert.equal(r.structurallyConsistent,true);assert.equal(r.state,'blocked');assert.equal(r.capabilities.registered,false);assert.equal(r.capabilities.paste,false);assert.equal(rejectUntrustedRegistration(fixture()).reason,'TRUSTED_BINDING_PROVIDER_UNAVAILABLE');});
test('claimed trust flags cannot promote synthetic evidence',()=>{for(const mode of ['trusted','helper-signed','provider-bound',null]){const m=fixture();m.evidenceMode=mode;assert.equal(check(m).reason,'UNTRUSTED_REGISTRATION_INPUT');}});
test('PID reuse and console remapping invalidate evidence',()=>{for(const key of ['clientPid','clientStartTicks','hostPid','hostStartTicks','consoleId']){const m=fixture();m.observation[key]=typeof m.observation[key]==='number'?99:'changed';assert.equal(check(m).reason,'REGISTRATION_PROCESS_OR_CONSOLE_CHANGED');}});
test('ownership logon changes and ambiguous panes fail',()=>{for(const key of ['ownerId','logonSessionId']){const m=fixture();m.observation[key]='other';assert.equal(check(m).reason,'REGISTRATION_OWNER_OR_SESSION_CHANGED');}for(const bindings of [[],['pane-2'],['pane-1','pane-2']]){const m=fixture();m.observation.paneBindings=bindings;assert.equal(check(m).reason,'REGISTRATION_ASSOCIATION_AMBIGUOUS');}});
test('expiry future observations revocation and generations fail',()=>{for(const mutate of [m=>m.claim.expiresAtMs=11000,m=>m.claim.expiresAtMs=20000,m=>m.observation.observedAtMs=11001,m=>m.observation.observedAtMs=0]){const m=fixture();mutate(m);assert.equal(check(m).reason,'REGISTRATION_EXPIRED');}for(const mutate of [m=>m.revoked=true,m=>m.revoked=undefined,m=>m.observation.generation='g2']){const m=fixture();mutate(m);assert.equal(check(m).reason,'REGISTRATION_REVOKED_OR_REPLACED');}});
test('WSL tty reuse reboot distro and Linux process reuse fail independently',()=>{for(const key of ['distroId','bootId','pid','startTicks','tty','sessionId']){const m=fixture();m.observation.wsl[key]=key==='pid'?999:'changed';assert.equal(check(m).reason,'REGISTRATION_WSL_SESSION_CHANGED');}const m=fixture();delete m.observation.wsl;assert.equal(check(m).reason,'REGISTRATION_WSL_EVIDENCE_MISSING');});
test('bounded invalid proposal fuzz always remains blocked',()=>{for(const value of [null,{},[],true,0,'claimed proof',{'__proto__':{registered:true}}]){const r=check(value);assert.equal(r.state,'blocked');assert.equal(r.capabilities.registered,false);}for(let i=0;i<100;i++){const m=fixture();m.claim.clientPid=i%2?-i:4294967295+i;assert.equal(check(m).reason,'REGISTRATION_IDENTITY_INVALID');}});
