import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,readFile,writeFile,rm,cp} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {execFileSync} from 'node:child_process';import {pathToFileURL} from 'node:url';import {createHash,randomUUID} from 'node:crypto';
const hash=b=>createHash('sha256').update(b).digest('hex'),oldCommit='5db8ffb0f84b71e53c45d40ef5f820de15059f14';
function downloadFor(manifest,archive){const url=`https://github.com/osmelpv/dot-connector/releases/download/v${manifest.version}/`,mb=Buffer.from(JSON.stringify(manifest));return async target=>{
 if(target.endsWith('/git/ref/tags/v'+manifest.version))return Buffer.from(JSON.stringify({object:{type:'commit',sha:manifest.commit}}));
 if(target.endsWith('/releases/tags/v'+manifest.version))return Buffer.from(JSON.stringify({id:19,draft:false,prerelease:true,published_at:'2026-10-07T00:00:00Z',tag_name:'v'+manifest.version,assets:[{name:'update-manifest-'+manifest.version+'.json',state:'uploaded',browser_download_url:url+'update-manifest-'+manifest.version+'.json',digest:'sha256:'+hash(mb)},{name:manifest.archive,state:'uploaded',browser_download_url:url+manifest.archive,size:archive.length,digest:'sha256:'+hash(archive)}]}));
 if(target===url+manifest.archive)return archive;if(target===url+'update-manifest-'+manifest.version+'.json')return mb;throw Error('UNEXPECTED_NETWORK_REQUEST');};}
test('actual unmodified 0.1.8 updater accepts original candidate runtime archive, preserves checksums and rolls back',async t=>{
 const parent=await mkdtemp(path.join(tmpdir(),'dot-legacy-compat-'));t.after(()=>rm(parent,{recursive:true,force:true}));const legacyDir=path.join(parent,'legacy','src');await mkdir(legacyDir,{recursive:true});
 const git=(...args)=>execFileSync('git',args,{maxBuffer:10*1024*1024});await writeFile(path.join(legacyDir,'update-release.mjs'),git('show',oldCommit+':src/update-release.mjs'));const legacy=await import(pathToFileURL(path.join(legacyDir,'update-release.mjs')));
 const oldBytes=git('archive','--format=tar.gz','--prefix=dot-connector/',oldCommit),oldFiles={};for(const name of git('ls-tree','-r','--name-only',oldCommit).toString().trim().split('\n'))oldFiles[name]=hash(git('show',oldCommit+':'+name));
 const old={schema:1,repository:'osmelpv/dot-connector',version:'0.1.8',commit:oldCommit,archive:'dot-connector-0.1.8-source.tar.gz',size:oldBytes.length,sha256:hash(oldBytes),files:oldFiles};
 const bundle=path.join(parent,'bundle');execFileSync(process.execPath,['scripts/package-local.mjs',bundle]);const candidate=JSON.parse(await readFile(path.join(bundle,'local-manifest.json'))),bytes=await readFile(path.join(bundle,candidate.archive));
 assert.equal(candidate.files['src/native-console-prototype.cs'],undefined);assert.equal(candidate.files['test/console-prototype.test.mjs'],undefined);assert.ok(candidate.files['src/native-control-host.cs']);assert.ok(candidate.files['test/update-release.test.mjs']);
 legacy.validateManifest(candidate,candidate.version,candidate.commit);legacy.unpackArchive(bytes,candidate);
 const forbidden=structuredClone(candidate);forbidden.files['src/native-console-prototype.cs']='a'.repeat(64);assert.throws(()=>legacy.validateManifest(forbidden,forbidden.version,forbidden.commit),/INVALID_MANIFEST/);
 const corrupt=Buffer.from(bytes);corrupt[0]^=1;assert.throws(()=>legacy.unpackArchive(corrupt,candidate),/CHECKSUM/);
 const root=path.join(parent,'installed'),prepare=async stage=>cp(path.resolve('node_modules'),path.join(stage,'node_modules'),{recursive:true});
 await legacy.bootstrap(root,'0.1.8',{download:downloadFor(old,oldBytes),prepare});await writeFile(path.join(root,'user','config.json'),'opaque config');const lease=randomUUID();await writeFile(path.join(root,'lifecycle.lock'),JSON.stringify({lease}));
 const before=await readFile(path.join(root,'current.json'));const brokenDownload=downloadFor(candidate,corrupt);await assert.rejects(legacy.runUpdate(root,lease,{version:candidate.version},{download:brokenDownload,prepare}),/ARCHIVE_METADATA_MISMATCH|CHECKSUM/);assert.deepEqual(await readFile(path.join(root,'current.json')),before);
 const updated=await legacy.runUpdate(root,lease,{version:candidate.version},{download:downloadFor(candidate,bytes),prepare});assert.equal(updated.version,candidate.version);assert.equal(await readFile(path.join(root,'user','config.json'),'utf8'),'opaque config');
 const current=JSON.parse(await readFile(path.join(root,'current.json')));assert.equal(current.previous.commit,oldCommit);await legacy.verifyInstalled(root,current);const health=JSON.parse(execFileSync(process.execPath,[path.join(root,'releases',current.directory,'scripts/dot-connector.mjs'),'version']).toString());assert.equal(health.version,candidate.version);
 const rollback=await legacy.runUpdate(root,lease,{rollback:true});assert.equal(rollback.version,'0.1.8');assert.equal(JSON.parse(await readFile(path.join(root,'current.json'))).commit,oldCommit);assert.equal(await readFile(path.join(root,'user','config.json'),'utf8'),'opaque config');
});
